apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    argocd.argoproj.io/instance: apps
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: config
  source:
    helm:
      valueFiles:
      - values.yaml
    path: charts/cert-manager
    repoURL: <REPO_URL>
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true