apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  project: config
  sources:
    - chart: cloudnative-pg
      repoURL: https://cloudnative-pg.io/charts/
      targetRevision: 0.22.0
      helm:
        values: |
          monitoring:
            podMonitorEnabled: true
          replicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnative-pg
