apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  labels:
    argocd.argoproj.io/instance: apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.16.0
    chart: loki
    helm:
      values: |
        global:
          dnsService: rke2-coredns-rke2-coredns
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: 'filesystem'
          schemaConfig:
            configs:
            - from: "2024-01-01"
              store: tsdb
              index:
                prefix: loki_index_
                period: 24h
              object_store: filesystem
              schema: v13
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClass: longhorn
        read:
          replicas: 0
        backend:
          replicas: 0
        write:
          replicas: 0
        chunksCache:
          enabled: false
        monitoring:
          serviceMonitor:
            enabled: true
  project: config
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
