apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: apps
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.16.6
    chart: promtail
    helm:
      values: |-
        promtail:
          enabled: true
  project: config
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
