{{- range $k, $v := .Values.l2advertisements }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ quote $k }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "metallb.labels" $ | nindent 4 }}
spec:
  {{- toYaml $v | nindent 2 }}

---
{{- end }}
