{{- define "cert-manager.certificate" -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: cert-manager
spec:
  secretName: {{ .Values.certificate.name }}
  issuerRef:
    name: {{ .Values.certificate.issuerName }}
    kind: ClusterIssuer
  commonName: <COMMON_NAME>
  dnsNames:
    - <DOMAIN>
    - <*.DOMAIN>
{{- end }}

{{- if .Values.certificate }}
{{- include "cert-manager.certificate" . }}
{{- end }}
