{{- range $k, $v := .Values.clusterIssuers }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ quote $k }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    {{- include "cert-manager.labels" $ | nindent 4 }}
spec:
  {{- toYaml $v | nindent 2 }}

---
{{- end }}
